name: 雨云产品自动续期

on:
  # 北京时间每天 00:00 = UTC 16:00
  schedule:
    - cron: '0 16 * * *'
  # 支持手动触发
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: 调用雨云续期 API
        run: |
          curl --location --request POST 'https://api.v2.rainyun.com/product/point_renew' \
            --header 'x-api-key: ${{ secrets.RAIN_API }}' \
            --header 'rain-dev-token: {{rain-dev-token}}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "duration_day": ${{ secrets.DURATION_DAY }},
              "product_id": ${{ secrets.PRODUCT_ID }},
              "product_type": "${{ secrets.PRODUCT_TYPE }}"
            }'
